### ISSUE TITLE
Note: Kernel support for ovpn-dco missing, disabling data channel offload.

### ISSUE THREAD

**Issue by Comandante1977** [OpenVPN/ovpn-dco#26]
Clone module from git. Compiled.
Run modprobe ovpn-dco-v2
Installed Openvpn 2.6.0 from deb repo (dco enabled)

And in anyway I've got "Note: Kernel support for ovpn-dco missing, disabling data channel offload."
error in openvpn log

**Comment by cron2** [comment]
Hi,

On Thu, Mar 23, 2023 at 07:07:29AM -0700, Comandante1977 wrote:
> Clone module from git. Compiled.
> Run modprobe ovpn-dco-v2
> Installed Openvpn 2.6.0 from deb repo (dco enabled)
> 
> And in anyway I've got "Note: Kernel support for ovpn-dco missing, disabling data channel offload."
> error in openvpn log

ovpn-dco-v2 is only compatible with OpenVPN 2.6.2 and later versions.

For 2.6.0, just use the debian-provided ovpn-dco kernel module.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***
