### ISSUE TITLE
tcp.c:482:31: error: assignment to ‘int (*)(struct sock *, struct msghdr *, size_t,  int,  int,  int *)’

### ISSUE THREAD

**Issue by prchal** [OpenVPN/ovpn-dco#54]
While compiling I get this error:
/home/prchal/cdubian/ovpn-dco/drivers/net/ovpn-dco/tcp.c: In function ‘ovpn_tcp_init’:
/home/prchal/cdubian/ovpn-dco/drivers/net/ovpn-dco/tcp.c:482:31: error: assignment to ‘int (*)(struct sock *, struct msghdr *, size_t,  int,  int,  int *)’ {aka ‘int (*)(struct sock *, struct msghdr *, unsigned int,  int,  int,  int *)’} from incompatible pointer type ‘int (*)(struct sock *, struct msghdr *, size_t,  int,  int *)’ {aka ‘int (*)(struct sock *, struct msghdr *, unsigned int,  int,  int *)’} [-Werror=incompatible-pointer-types]
  482 |         ovpn_tcp_prot.recvmsg = ovpn_tcp_recvmsg;
      |                               ^
cc1: some warnings being treated as errors

I did crosscompilation on Ubuntu 22.04:
ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabi- make KERNEL_SRC=/home/prchal/cdubian/linux/

**Comment by prchal** [comment]
vanilla 5.17.15

**Comment by ordex** [comment]
Indeed there was a mistake in the ifdef condition. As of now if says "<5.16", but it should be "<5.19".
I'd like to credit you as reporter (Rported-by tag). What name/email should I use?

**Comment by prchal** [comment]
Jiri Prchal
jiri.prchal@aksignal.cz

**Comment by ordex** [comment]
Thanks a lot. I just pushed c24380cdb8f5 which fixes this issue.
