### ISSUE TITLE
DCO and ipv6

### ISSUE THREAD

**Issue by atoy40** [OpenVPN/ovpn-dco#55]
Hello,

I tested to connect to my server through his ipv6 public address. The connexion has established without any issue, but the performance looks really bad ! It drop from 80mb/s to less than a mb/s in a simple speed test.
Simple question, is DCO limited to the ipv4 socket ?

One more information, my server is configured with "proto udp6", has both an ipv4 and an ipv6 and is fast when i'm connecting to the v4 address, slow on the v6.

Thanks
Anthony.

**Comment by ordex** [comment]
Hi @atoy40 and thanks for the report. There is no limitation on IPv6 therefore no drop is really expected.
Have you checked whether you have some MTU issue which is causing packets to be dropped due to their size?

**Comment by cron2** [comment]
DCO is incompatible with `fragment` - so when that option is used, OpenVPN disables use of DCO.

`mssfix` is communicated to kernel, but as far as I know, Linux kernel side is not handling it yet ("to be implemented later, there might be an existing function to do this, ...").  So with Linux DCO it's a no-op today.

**Comment by ordex** [comment]
closing this issue as no direct problem with IPv6 exists.
