### ISSUE TITLE
Kernel ver 6.12-rc7: Kernel support for ovpn-dco missing, disabling data channel offload

### ISSUE THREAD

**Issue by Cerberios** [OpenVPN/ovpn-dco#71]
I've tested kernel version 6.12-rc7 and was unable to use openvpn-dco. Is current client support new kernel? 

The error:

Note: Kernel support for ovpn-dco missing, disabling data channel offload.
OpenVPN 2.7_git [git:HEAD/d52ea247d9dec526] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] [DCO] built on Nov 13 2024
DCO version: N/A

Thanks You for answer.

**Comment by Cerberios** [comment]
Hello there, thank You for answer.
Let me describe step by step what I've did. I use Gentoo as base OS.
1) Downloaded kernel linux-6.12-rc7.tar.gz from site.
2) Unpacked it and applied patch from resource:
https://raw.githubusercontent.com/CachyOS/kernel-patches/refs/heads/master/6.12/0010-openvpn-dco.patch
It's applied OK without errors.
3) Then make localmodconfig && make menuconfig
3.1) Found and selected openvpn-dco section and checked as module enabled.
4) Then: make prepare && make modules_prepare && make -j15 all && make modules_install && make install
5) Reboot.
6) Made lsmod | grep -i vpn --> no vpn module at all
I can provide more info / logs if necessary. 
Unfortunately, I am not a programmer, but I'd like to use openvpn-dco for sure on daily bases.
Thanks!

**Comment by ordex** [comment]
> https://raw.githubusercontent.com/CachyOS/kernel-patches/refs/heads/master/6.12/0010-openvpn-dco.patch

as you can see this patch does not come from any official OpenVPN repository, therefore we cannot assist with that.

You should reach out to who has created that patch (for example by opening an issue with CachyOS) and ask them what is this all about and how to make that work on linux-6.12.

At a very first glance, this seems to be a once-patch port of the new 'ovpn' kernel module which is not yet supported by openvpn2.

Ina ny case, you should really ask them.

**Comment by ptr1337** [comment]
> > [CachyOS/kernel-patches@`refs`/heads/master/6.12/0010-openvpn-dco.patch (raw)](https://raw.githubusercontent.com/CachyOS/kernel-patches/refs/heads/master/6.12/0010-openvpn-dco.patch)
> 
> as you can see this patch does not come from any official OpenVPN repository, therefore we cannot assist with that.
> 
> You should reach out to who has created that patch (for example by opening an issue with CachyOS) and ask them what is this all about and how to make that work on linux-6.12.
> 
> At a very first glance, this seems to be a once-patch port of the new 'ovpn' kernel module which is not yet supported by openvpn2.
> 
> In any case, you should really ask them.

The patch is coming from lkml, which is hopefully coming from the official openvpn members:
https://lore.kernel.org/lkml/20241029-b4-ovpn-v11-0-de4698c73a25@openvpn.net/

**Comment by cron2** [comment]
OpenVPN 2.6.0+ supports the "old" DCO module which is maintained in https://github.com/OpenVPN/ovpn-dco.

On the way towards kernel inclusion, feedback from kernel developers required very large changes to the module itself, and also to the API it uses to communicate with userspace.  v11 of that is what you have on the lkml list.  OpenVPN "userspace" does not currently support the new API - we're waiting until it's clear how the kernel API looks like, and then git master will be changed to use the new API, and this will be released as 2.7.0 early 2025.

So, 2.6.x will never support the upcoming in-tree version.  Use the ovpn-dco github version for that.
2.7.x will never support the old out-of-tree DCO version.  Use the in-kernel version with 2.7.x

The git master branch will, at some point, change from one to the other.  So follow the changelog closely :-)

**Comment by ptr1337** [comment]
Thank you, ill drop the patch in the upcoming release.

**Comment by ordex** [comment]
Thanks @cron2 for clarifying this.
@ptr1337 I think you got all needed data points (and yes, it's me posting on lkml :-) )

If you want your users to support DCO with OpenVPN 2.6, please include the out-of-tree kernel module coming from https://github.com/OpenVPN/ovpn-dco

**Comment by ordex** [comment]
> Hello, thank You for education, it was great lecture about Linux functionality. Please detail a bit next point: I've compiled yday https://github.com/OpenVPN/openvpn3-linux And this generation of VPN seems also does not support latest `ovpn` from kernel 6.12-rc7 Is it possible to implement this support? Thanks you very much for clarification!

Support for 'ovpn' is in WIP state because ovpn's API is NOT stable yet.
Support for 'ovpn' will be added to both openvpn2 and openvpn3 after 'ovpn' has been merged upstream.

For the time being you must use `ovpn-dco-v2` from the `ovpn-dco` repo with both openvpn2 and 3
