### ISSUE TITLE
Compilation fail with ovpn-dco-0.2.20240712 and kernel 6.12

### ISSUE THREAD

**Issue by Cerberios** [OpenVPN/ovpn-dco#72]
Compilation fail with ovpn-dco-0.2.20240712 and kernel 6.12

/var/tmp/portage/net-vpn/ovpn-dco-0.2.20240712/work/ovpn-dco-0.2.20240712/drivers/net/ovpn-dco/main.c: In function ‘ovpn_setup’:
/var/tmp/portage/net-vpn/ovpn-dco-0.2.20240712/work/ovpn-dco-0.2.20240712/drivers/net/ovpn-dco/main.c:130:47: error: ‘NETIF_F_LLTX’ undeclared (first use in this function); did you mean ‘NETIF_F_LRO’?
  130 |         netdev_features_t feat = NETIF_F_SG | NETIF_F_LLTX |
      |                                               ^~~~~~~~~~~~
      |                                               NETIF_F_LRO
/var/tmp/portage/net-vpn/ovpn-dco-0.2.20240712/work/ovpn-dco-0.2.20240712/drivers/net/ovpn-dco/main.c:130:47: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [scripts/Makefile.build:229: /var/tmp/portage/net-vpn/ovpn-dco-0.2.20240712/work/ovpn-dco-0.2.20240712/drivers/net/ovpn-dco/main.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [scripts/Makefile.build:478: /var/tmp/portage/net-vpn/ovpn-dco-0.2.20240712/work/ovpn-dco-0.2.20240712/drivers/net/ovpn-dco] Error 2
make[2]: *** [/usr/src/linux-6.12.0-gentoo/Makefile:1946: /var/tmp/portage/net-vpn/ovpn-dco-0.2.20240712/work/ovpn-dco-0.2.20240712] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-6.12.0-gentoo'
make: *** [Makefile:51: all] Error 2

**Comment by ordex** [comment]
Thanks for reporting, however I did not have time yet to port ovpn-dco to 6.12 - will likely do in the coming days.

Patches are welcome!

**Comment by ordex** [comment]
> seems to fix,but i'm not sure

NO - DON' DO THAT.

dev->lltx is a bool, you can blindly OR it with other bits.
As a quick workaround, just delete NETIF_F_LLTX.

**Comment by ordex** [comment]
ovpn-dco now compiles on 6.12, thanks to 0935edd8569b
