### ISSUE TITLE
What's the kernel version support for ovpn-dco?

### ISSUE THREAD

**Issue by Fashaun** [OpenVPN/ovpn-dco#8]
as title

**Comment by ordex** [comment]
It should compile fine and work starting with linux 5.1.
Older versions may work, but can't guarantee.

**Comment by ptr1337** [comment]
Just a little questions:
Will be a new patchset sent for the 6.1 Kernel? I tried to port some stuff from this repo back, but dmesg gives a error out.
DKMS works well with git, but I like to have it built in into the kernel.

Using it since some time with the 6.0 Kernel and it is working really well.

Was the latest log with the backports to 6.1 I tried:
```
[    0.352999] OpenVPN data channel offload (ovpn-dco) 2.0.0 -- (C) 2020-2022 OpenVPN, Inc.
[    0.353007] ------------[ cut here ]------------
[    0.353007] WARNING: CPU: 2 PID: 1 at net/netlink/genetlink.c:383 genl_register_family+0xcd/0x750
[    0.353011] Modules linked in:
[    0.353013] CPU: 2 PID: 1 Comm: swapper/0 Not tainted 6.1.0-rc8-1-cachyos-rc #1 e190906703ac81fb36cdc3287d2dd98895b660f8
[    0.353014] Hardware name: ASUS System Product Name/PRIME B550-PLUS, BIOS 2803 04/27/2022
[    0.353015] RIP: 0010:genl_register_family+0xcd/0x750
[    0.353017] Code: 48 83 7c 24 28 00 0f 84 46 03 00 00 48 8b 04 24 0f b6 6c 24 44 40 3a 68 28 0f 82 8a 02 00 00 80 7c 24 47 00 0f 84 7f 02 00 00 <0f> 0b 41 bd ea ff ff ff 48 8b 44 24 78 65 48 2b 04 25 28 00 00 00
[    0.353018] RSP: 0018:ffffb214c0063de0 EFLAGS: 00010206
[    0.353019] RAX: ffffffffb719e100 RBX: ffffffffb7f153ab RCX: ffffffffb719e100
[    0.353019] RDX: ffffb214c0063df8 RSI: 0000000000000000 RDI: ffffffffb719e100
[    0.353020] RBP: 0000000000000001 R08: ffffffffb7999090 R09: ffffffffb80b8b80
[    0.353021] R10: ffffb214c0063d38 R11: ffff8cd9ef2a88a8 R12: 0000000000000009
[    0.353021] R13: ffffffffb8024030 R14: 0000000000000000 R15: 0000000000000009
[    0.353022] FS:  0000000000000000(0000) GS:ffff8cd9cea80000(0000) knlGS:0000000000000000
[    0.353023] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    0.353023] CR2: 0000000000000000 CR3: 0000000199410000 CR4: 0000000000750ee0
[    0.353024] PKRU: 55555554
[    0.353025] Call Trace:
[    0.353026]  <TASK>
[    0.353027]  ? ovpn_netlink_notify+0xf0/0xf0
[    0.353030]  ? spi_init+0xc4/0xc4
[    0.353032]  ovpn_netlink_register+0x12/0x3e
[    0.353034]  ? spi_init+0xc4/0xc4
[    0.353035]  ovpn_init+0x4c/0x80
[    0.353036]  ? spi_init+0xc4/0xc4
[    0.353037]  do_one_initcall+0x59/0x220
[    0.353040]  kernel_init_freeable+0x1eb/0x228
[    0.353042]  ? rest_init+0xd0/0xd0
[    0.353044]  kernel_init+0x16/0x130
[    0.353045]  ret_from_fork+0x22/0x30
[    0.353047]  </TASK>
[    0.353047] ---[ end trace 0000000000000000 ]---
[    0.353048] ovpn: can't register netlink family
[    0.353050] fbcon: Taking over console
[    0.353055] ovpn: initialization failed, error status=-22
````

**Comment by ordex** [comment]
yes and thanks for pointing this out. it's on my todo list!

**Comment by ptr1337** [comment]
@ordex 

Hi. Sorry for bothering.
Since openvpn 2.6 now introduced dco, would it possible to create a kernel patch again and consider to upstream it?
Would be really nice, I prefer a patch over building dkms modules all time.

Since im maintainer of a much used custom kernel, it would be very nice to include openvpn dco as default. :)

Regards

**Comment by xevilstar** [comment]
II generally agree  with your idea and I support it but, It would be
necessary for example debian to move the dco away from dkms and put it
inside the default .config as module for everyone.
You should also open a bug to the debian mentors list

**Comment by ordex** [comment]
> Hi. Sorry for bothering. Since openvpn 2.6 now introduced dco, would it possible to create a kernel patch again and consider to upstream it? Would be really nice, I prefer a patch over building dkms modules all time.

Hi, a first patchset was already sent to the kernel mailing list, however, after further discussion at Netdev 0x16 in Lisbon, several changes are required before a new patchset can be provided, and those changes are currently work in progress :)

**Comment by huangya90** [comment]
> > Hi. Sorry for bothering. Since openvpn 2.6 now introduced dco, would it possible to create a kernel patch again and consider to upstream it? Would be really nice, I prefer a patch over building dkms modules all time.
> 
> Hi, a first patchset was already sent to the kernel mailing list, however, after further discussion at Netdev 0x16 in Lisbon, several changes are required before a new patchset can be provided, and those changes are currently work in progress :)

@ordex, any meeting minutes about required changes at Nexdev 0x16 you can share? Thank you.

**Comment by ordex** [comment]
Not really - the most important points are:
* restructure netlink API (90% done)
* use transport socket to send an receive packets to and from userspace (TCP is requiring a bit more time than expected)
